name: Trigger API Automation

on:
  push:
    branches:
      - master   # change if your branch is main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Automation Repo
        run: |
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.API_TEST_TRIGGER_TOKEN }}" \
            https://api.github.com/repos/roshaniwagh/api.swagh.in/dispatches \
            -d '{"event_type":"run-api-tests"}')

          echo "HTTP Status: $RESPONSE"
          cat response.txt

          if [ "$RESPONSE" != "204" ]; then
            echo "Dispatch failed!"
            exit 1
          fi